monitoring:
  interval: 60

thresholds:
  cpu:
    warning: 85
    critical: 95
    recovery: 75
  
  ram:
    warning: 85
    critical: 95
    recovery: 80

  disk:
    temperature:
      warning: 65
      critical: 75
      recovery: 55

    usage:
      warning: 80
      critical: 90
      recovery: 75

docker:
  monitored_containers:
  - immich_server
  - immich_postgres
  - immich_redis
  - vaultwarden